### ISSUE TITLE
Missing right control

### ISSUE THREAD

**Issue by FQQD** [fieldOfView/Cura-OctoPrintPlugin#281] opened 2022-06-12 12:24 UTC
I dont know why, but I'm missing the right arrow to move the printer. I reinstalled my OS and it worked fine before :/

Cura 4.4.1 running on Feren OS Linux
OctoPrintPlugin v3.7.2
OctoPrint Version 1.7.3
Anycubic Mega Zero 2.0

![image](https://user-images.githubusercontent.com/96952506/173233002-f75ca623-baf0-4f94-b1be-26d027a47411.png)

**Comment by fieldOfView** [comment] 2022-06-12 12:36
This was fixed in Cura 4.6, two years ago; see https://github.com/Ultimaker/Cura/pull/7126

You may want to use the AppImage version of Cura, which is less likely to be affected by issues like this because it includes a known-working combination of dependencies.

**Closed by fieldOfView** 2022-06-12 12:36 UTC

**Comment by fieldOfView** [comment] 2022-06-12 12:38
Also a duplicate of https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/149
