### ISSUE TITLE
Can not see OctoPi camera in Cura 4.1

### ISSUE THREAD

**Issue by bill-orange** [fieldOfView/Cura-OctoPrintPlugin#116] opened 2019-05-31 22:25 UTC
I am running OctoPi with a Pi camera hooked up to the camera port. The camera can be seen through my network without any issues. I am running Cura ver 4.1 on PC which is able to see the camera. I loaded the plug-in, set up the API string, rebooted, etc. I can monitor the printer without any issues. All the data I expect shows up except I do not see the camera. There do not seem to be any settings to confirm that Cura is looking at the right IP. 

Can I fix this?  Suggestions?

**Comment by fieldOfView** [comment] 2019-06-01 05:10
Are you sure you checked the checkbox to display the camera in the Connect to OctoPrint dialog?

Can you post your logs somewhere (dropbox, google drive, pastebin)? See Help -> Show configuration folder. The file you are looking for is named Cura.log

**Comment by bill-orange** [comment] 2019-06-01 13:32
Double and triple checked it!

Here is the log:

https://1drv.ms/u/s!AmXKqAwyCrbxiL5bUYI5DGG-gGM-UQ

**Comment by pyrokidd89** [comment] 2019-06-03 23:56
I have the same issue.

**Comment by bill-orange** [comment] 2019-06-04 00:08
@pyrokidd89 Probably be a good idea to post your log file too.

**Comment by pyrokidd89** [comment] 2019-06-04 00:26
[cura.log](https://github.com/fieldOfView/Cura-OctoPrintPlugin/files/3249960/cura.log)

**Comment by bill-orange** [comment] 2019-06-04 00:35
This is common to both your log file and mine.

2019-06-03 19:55:27,481 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [369]: file:///E:/Programs/Ultimaker Cura 4.1/resources/qml/RoundedRectangle.qml:68: TypeError: Cannot read property of null

**Comment by dragon076** [comment] 2019-06-04 05:08
Have the same problem as well. I have the creawsome add-on install now but was still seeing the same problem without it. What i did notice is before i start the print i go and reconnect the printer and un-tick and re-tick the webcam box sometimes it works again. Log attached.

[cura.log](https://github.com/fieldOfView/Cura-OctoPrintPlugin/files/3250606/cura.log)

**Comment by fieldOfView** [comment] 2019-06-04 07:06
It would be helpful if you could let me know if the same problem occurs with Cura 4.0 and the current version of the plugin (3.5.5).

**Comment by bill-orange** [comment] 2019-06-04 13:49
I have Cura 4.0 on a spare machine.  The current plugin works fine on Cura 4.0.

**Comment by fieldOfView** [comment] 2019-06-05 05:49
> The current plugin works fine on Cura 4.0.

Then I am going to have to hunt in Cura what changed to break things.

**Comment by tjones99** [comment] 2019-06-06 21:45
I had the same issue and just did two things so at first I wasn't sure what fixed it, but I just did a test and now know... 

I just did an Octoprint upgrade to 1.3.11... turns out that did not fix the issue... but nice to be current... 

What fixed it was reconnecting to Octoprint in Cura. I went in to manage printers, and into the connect to Octoprint dialog. There was already my auto discovered network instance of Octorpint named octopi._octoprint._tcp.local that I was connected to (and successfully printing and managing no issues) but I added a new connection and put in the specific IP address of my Octoprint server and I literally copied the API key from the octopi._octoprint._tcp.local and pasted it into my new connection I was making and clicked Connect and my webcam instantly appeared. 

I then went back and connected back to octopi._octoprint._tcp.local and webcam view disappeared. Reconnected to my newly created connection, back... 

So I got it working... but do not know why one works and the other doesn't...

**Comment by bill-orange** [comment] 2019-06-06 22:00
Interesting. That should give @fieldOfView a hint as to what change in Cura 4.1 upset the apple cart. I might be with posting the log where you switched from one to the other.

**Comment by tjones99** [comment] 2019-06-07 01:26
Attaching two log files. I deleted the log file, launched Cura and went to monitor and saw webcam and exited and saved that small log. 
Then I relaunched Cura and set it to the failing Octoprint connection, exited, deleted that log then relaunched Cura and went to monitor (no webcam) and exited. Smallest possible log. 

My view of the log tells me little about what is failing..

[curaoctoprint.zip](https://github.com/fieldOfView/Cura-OctoPrintPlugin/files/3264041/curaoctoprint.zip)

**Comment by m0oml** [comment] 2019-06-07 16:10
I have the same issue in 4.1 works fine in 4 if you go manage printers and click the connect octoprint button it comes back but I have to do it every time

**Comment by tjones99** [comment] 2019-06-07 16:15
If you create a new connection using the address instead of the auto discovered instance (helps if you assign a static Ip using a shop reservation in your router) then no need to disconnect and connect.

**Comment by bill-orange** [comment] 2019-06-07 16:20
Not a good long term solution but that does appear to work.

**Comment by rmaes4** [comment] 2019-06-19 18:02
+1 having the same problem

**Comment by anduchs** [comment] 2019-06-23 00:05
I can confirm. Manually adding Octoprint via IP works, whilst using autodiscovered Octoprint does not work. Cura 4.1 with Creawesome here.

**Comment by fieldOfView** [comment] 2019-06-26 17:00
This should be fixed with https://github.com/fieldOfView/Cura-OctoPrintPlugin/commit/1c5d42a2c00b7bb58578ea5817d6b48e4aee3235. I will do some more testing and publish an updated version to the Marketplace.

This was one of those pesky issues that did not manifest when running Cura from source. I also did not have an OctoPrint instance with a camera for a while, which made debugging this harder as you can imagine. Thanks for reporting, all.

**Comment by fieldOfView** [comment] 2019-06-27 11:33
Please test this version:
http://files.fieldofview.com/cura/OctoPrintPlugin-v6.0.0-2019-06-27T11_31_22Z.curapackage
To install, drop the downloaded file into a running Cura application window and restart Cura.

**Comment by elboletaire** [comment] 2019-06-27 11:38
I tried it yesterday and I can confirm it now works properly with autodiscovery (I'm updating from source).

**Comment by fieldOfView** [comment] 2019-06-27 18:57
I have submitted a fixed version to the Marketplace, which should be available soon(ish).

**Closed by fieldOfView** 2019-06-27 18:57 UTC
Labels: info needed
