### ISSUE TITLE
Cura 4.8 + Octoprint Unable to Connect / Printer offline

### ISSUE THREAD

**Issue by bitboy85** [fieldOfView/Cura-OctoPrintPlugin#220] opened 2021-01-12 17:48 UTC
Hi,

i'm using Cura 4.8 and octoprint 1.5.2
when i try to print it says printer offline.

Then i open the configuration screen select "connect to octoprint" message "checking api key" appears followed by "octoprint is not available"
If i now cut and paste the excact same api key it seems to be connected, but it is still not possible to send the print job.
Closing and opening the settings window again will lead to "octoprint is not available"

I already recreated the connection and tried the "master" api key but with same result.

Edit: Sadly this is not easy reproducible but i've seen it many times now.

Background: My printer is connected by a wifi wall socket to turn it off and on. I have a menu in octoprint for this.

usually i do this:
1. open cura and do the slice settings
2. open octoprint page and turn on printer with the help of the wifi wall socket
3. connect the printer
4. try to print via octoprint within cura

It seems to work if i first turn on and connect the printer in octoprint, and then open cura. After this i cannot reproduce the issue no matter in what order i do the steps.

**Comment by geNAZt** [comment] 2021-02-28 07:49
I installed this plugin today and had a similar issue. I can't direct "Print on Octoprint" since it tells me that the printer is offline. When i enable "Connct to printer before sending printjob" it gets infinite loading on trying to connect.

If i queue from the infinite loading bar it loads the job onto the printer and i can start it from there. 

Cura Logs show this: 

```
2021-02-28 08:19:40,006 - DEBUG - [MainThread] OctoPrintPlugin.OctoPrintOutputDevice.requestWrite [446]: Sent command to connect printer to OctoPrint with current settings
2021-02-28 08:19:40,296 - WARNING - [MainThread] OctoPrintPlugin.OctoPrintOutputDevice._onRequestFinished [862]: Encountered unexpected printjob state: Detecting serial connection
```

It seems that it doesn't like when OctoPrint has autodetect serial on when connecting to it?

**Comment by fieldOfView** [comment] 2021-07-06 14:59
@bitboy85 since you have a workaround, and no way to reproduce this reliably, I am going to close this issue for now. Let me know if you find a way to reproduce this

@geNAZt you seem to have a different issue. See #161

**Closed by fieldOfView** 2021-07-06 14:59 UTC
