### ISSUE TITLE
Send to Octoprint without Printing

### ISSUE THREAD

**Issue by Metathesus** [fieldOfView/Cura-OctoPrintPlugin#197] opened 2020-09-25 12:04 UTC
Hello,
Wonderfull "plugin" that help a lot. Thank for it!
As an enhancement, Is it possible to add something like "Send GCode octoprint" without starting the print? 
So we can start the print from another device later or send files during a print?

**Comment by Turiok** [comment] 2020-10-01 11:09
Hi,

The plugin already do that.
![confOctoprint](https://user-images.githubusercontent.com/6814217/94802046-3ebf8680-03e7-11eb-9793-21bbd00a4eb4.jpg)

Disable the "Start printing job after uploading" in the manage printers configuration panel for octoprint

Kind regards
Turiok,

**Comment by fieldOfView** [comment] 2020-10-01 11:17
As @Turiok already said, that functionality is already available. Also a duplicate of #129, which is still under consideration. I am considering adding a second "output" labeled "Save to OctoPrint" in addition to the current "Print with OctoPrint".

**Closed by fieldOfView** 2020-10-01 11:17 UTC
