### ISSUE TITLE
Add ability to just print or just upload gcode from print dialog

### ISSUE THREAD

**Issue by MarcinOrlowski** [fieldOfView/Cura-OctoPrintPlugin#207] opened 2020-11-19 13:08 UTC
It would be great if I could decide if I want to print given object or just upload gcode to octoprint for storage. Currently I can do one of this thing at once and to switch the operation mode, I need to "Manage printers" and tweak my settings there. This is pretty annoying in longer run and I'd love to be able to either select specified operation in this dialog directly:

![plug](https://user-images.githubusercontent.com/8041294/99670368-b9646400-2a70-11eb-8e73-2d279b2f4242.png)

or have another dialog opened asking me for this.

**Comment by fieldOfView** [comment] 2020-11-19 13:34
Duplicate of https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/129

**Closed by fieldOfView** 2020-11-19 13:34 UTC
