### ISSUE TITLE
Can't connect Cura to Octoprint 1.5.1

### ISSUE THREAD

**Issue by ctwise** [fieldOfView/Cura-OctoPrintPlugin#212] opened 2020-12-06 20:46 UTC
First time using Octoprint and first time using Cura connector. I created an API key for my user, brought up Cura, brought up Connect to OctoPrint and entered the info for the octoprint server. I cliked on the 'Request...' button and a pop-up shows in Octoprint asking for approval. I press 'allow'. But on the Cura side it never changes from 'OctoPrint is not available'.

I put Wireshark on it and that just confuses me more. At either see '403 Forbidden' for each request or I see 202 waiting for approval messages.

I also never see my user in the 'User name' field under the API Key field.

Suggestions?

**Comment by ctwise** [comment] 2020-12-07 01:16
I've continued to dig and the plugin doesn't ask for a username and password even though access control is turned on in Octoprint. I tried filling in the username in the proxy settings but that didn't work. The User name field just stays blank.

I'm able to access the http://octopi:80/api/settings from my browser but I see this in the Cura logs:

2020-12-06 20:13:36,088 - WARNING - [MainThread] OctoPrintPlugin.DiscoverOctoPrintAction._onRequestFailed [442]: Connection refused or timeout when trying to access OctoPrint at http://octopi:80/api/settings

**Comment by ctwise** [comment] 2020-12-07 01:18
Discovery doesn't work because the printer is on a different network segment.

**Comment by fieldOfView** [comment] 2020-12-07 08:24
I think this is a duplicate of #211

**Comment by fieldOfView** [comment] 2020-12-07 08:27
> the plugin doesn't ask for a username and password

This is correct. The plugin uses keys instead of a username/password. This key has a user connected to it.

**Comment by ctwise** [comment] 2020-12-07 14:58
I don’t know if it’s the same problem or not. It’s not due to a timeout
according to the logs.

**Comment by fieldOfView** [comment] 2020-12-07 15:09
The only bit of log that you posted says:

OctoPrintPlugin.DiscoverOctoPrintAction._onRequestFailed [442]: **Connection refused or timeout** when trying to access OctoPrint at http://octopi:80/api/settings

**Comment by ctwise** [comment] 2020-12-07 15:56
That’s a very valid point. And I verified that you are correct. I increased
the timeout and it's working now. You can mark this as a duplicate of 211.
Thanks for setting me straight. :-)

**Closed** 2020-12-07 16:00 UTC
