### ISSUE TITLE
[Feature Request] Only upload to octoprint

### ISSUE THREAD

**Issue by bitboy85** [fieldOfView/Cura-OctoPrintPlugin#183] opened 2020-07-26 07:42 UTC
For me it woud be nice to have an additional option in the dropdownmenu in the bottom right corner allowing the gcode to only upload to octoprint without starting to print.

**Comment by fieldOfView** [comment] 2020-07-26 10:19
Duplicate of #129

**Closed by fieldOfView** 2020-07-26 10:19 UTC
