### ISSUE TITLE
Error on upload: 502 Bad Gateway (OctoPrint 1.4.0rc1)

### ISSUE THREAD

**Issue by Deneteus** [fieldOfView/Cura-OctoPrintPlugin#135] opened 2019-11-28 17:20 UTC
A newer version of Octoprint is out (OctoPrint: 1.4.0rc1) and with Cura 4.4.0 Stable when I send a file it now shows the files being sent by Cura and then ends with Bad Gateway Error.

I am assuming the plug-in needs to be updated for it to work properly?

![image](https://user-images.githubusercontent.com/6380390/69824165-93dfaa00-11d0-11ea-888b-526cf0ba82f0.png)

![image](https://user-images.githubusercontent.com/6380390/69824311-00f33f80-11d1-11ea-85e7-f9bf3e33a35e.png)

**Comment by fieldOfView** [comment] 2019-11-28 17:48
Thanks for reporting. I am seeing the same on my 1.4.0 RC1 installation. I'm not sure at this point if it is something the plugin is doing wrong or OctoPrint.

**Comment by fieldOfView** [comment] 2019-11-29 07:56
FYI, https://github.com/foosel/OctoPrint/issues/3358. Could you check your octoprint.log to see if there is a similar error in your logs?

I don't know if it is relevant yet, but what do you run OctoPrint on? If OctoPi, then what version of OctoPi?

**Comment by fieldOfView** [comment] 2019-11-29 10:22
See https://github.com/foosel/OctoPrint/issues/3349. This should be fixed with OctoPrint 1.4.0 RC2

**Closed** 2019-11-29 10:22 UTC
Labels: upstream

**Comment by nikon662** [comment] 2019-12-01 23:38
For a Quick fix I ran this code and restarted octoprint
`wget -O /home/pi/oprint/lib/python2.7/site-packages/octoprint/server/util/tornado.py https://raw.githubusercontent.com/foosel/OctoPrint/staging/devel/src/octoprint/server/util/tornado.py`
This is the first time I've tried to help someone on github so if I've done something wrong please let me know. Thanks :)

**Comment by fieldOfView** [comment] 2019-12-02 11:41
The problem is also fixed here: ab40c033cb36115575380c234340b893df091aad

**Comment by fieldOfView** [comment] 2019-12-02 15:37
OctoPrint 1.4.0 RC2 is now available, which should fix this bug from that side.

**Comment by Deneteus** [comment] 2019-12-04 18:02
I tested it yesterday and was able to send files with no problems with the RC2 update.
