### ISSUE TITLE
Cura 5.0 but Octoprint menu does not show up at all

### ISSUE THREAD

**Issue by Athanaetos** [fieldOfView/Cura-OctoPrintPlugin#274] opened 2022-05-19 00:49 UTC
Hi, 

I recently updated to Cura 5.0 and Octoprint 1.8.0. The issue is with Cura and that the plug-in settings do not show up in preferences. I don't know why.

**Comment by Athanaetos** [comment] 2022-05-19 00:51
![image](https://user-images.githubusercontent.com/10691281/169179223-444aec31-5871-42a3-81f3-2e0109e3b9fb.png)

**Comment by BaeByte** [comment] 2022-05-19 03:31
I can confirm same issue updated to octo 1.8 this afternoon shortly after cura to 5.0 and cannot see connect to octoprint the plugin was also updated from the marketplace 3.7.2

**Comment by fieldOfView** [comment] 2022-05-20 07:33
Please see https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/272
It looks like the plugin may not actually be installed, but Cura thinks it is.

**Comment by fieldOfView** [comment] 2022-05-20 08:37
Closing this as a duplicate of the other issue.

**Closed by fieldOfView** 2022-05-20 08:37 UTC
