### ISSUE TITLE
Sync Cura Preview render to Current print layer

### ISSUE THREAD

**Issue by Z3r0Auth** [fieldOfView/Cura-OctoPrintPlugin#241] opened 2021-06-28 22:46 UTC
Dunno if it's possible, but would love it as a feature to be able to see where the print is at through the rendered preview window of Cura. Figure precision following is out of the question, but at least layer height would give a good viewpoint of where it's at on the print of the model, much like the built in GCode Viewer on OctoPrint

**Comment by fieldOfView** [comment] 2021-06-29 09:19
Duplicate of #137. See my comment there: https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/137#issuecomment-562841499

**Closed by fieldOfView** 2021-06-29 09:19 UTC
