### ISSUE TITLE
cura 4.13.0 crashes on start-up with OctoPrintPlugin 3.7.2

### ISSUE THREAD

**Issue by KaiMartin** [fieldOfView/Cura-OctoPrintPlugin#297] opened 2022-09-21 18:21 UTC
My cura 4.13.0 from Debian testing crashes on start-up if OctoPrintPlugin 3.7.2 is installed. The appimage of cura does not segfault. This looks like the same problem that issue #289 complains about. However, I may provide an additional data point:
* The same cura install from Debian testing runs just fine with OctoPrintPlugin 3.6.0 .
* The problem is present in OctoPrintPlugin 3.7.0-DEV already.

Would it be worth the effort to bisect the version history and pinpoint the commit that introduced the breaking changes?

---<)kaimartin(>---

from the command line:
[cura-segfault.txt](https://github.com/fieldOfView/Cura-OctoPrintPlugin/files/9619362/cura-segfault.txt)

**Comment by fieldOfView** [comment] 2022-09-24 16:44
Duplicate of https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/295

**Closed by fieldOfView** 2022-09-24 16:44 UTC
