### ISSUE TITLE
Fatal Error Checking API Key

### ISSUE THREAD

**Issue by johnrbussard** [fieldOfView/Cura-OctoPrintPlugin#174] opened 2020-06-07 22:26 UTC
I thought this may be related to issue 173, but persists after updating the plugin by downloading from github too.

Cura will immediately crash whenever an API key is entered.  I have done a clean install of cura and the plugin.  

https://www.dropbox.com/s/xnkqmzhmlxldcrn/curaoctoprinterror.png?dl=0

https://www.dropbox.com/s/hoh8byk1itpi4x1/stderr.log?dl=0

I became aware of this problem because Cura would no longer send .ufp to octoprint, only .gcode.

**Comment by fieldOfView** [comment] 2020-06-08 06:23
I'm closing this as a duplicate of #173. That issue contains a link to a fixed version that you can manually install.

**Closed by fieldOfView** 2020-06-08 06:23 UTC
